version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: postgres_resposta_quente
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - resposta_quente_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  resposta_quente_app:
    build: ./../run
    image: resposta_quente:dev
    container_name: resposta_quente_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "9901:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - resposta_quente_network
volumes:
  postgres_data:

networks:
  resposta_quente_network: